{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cicd-app-chart.fullname" . }}
  labels:
    {{- include "cicd-app-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- if .Values.prNumber }}
    # Preprod: automatic host generation pr-{NUMBER}.app.local
    - host: "pr-{{ .Values.prNumber }}.{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cicd-app-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- else }}
    # Production: app.local
    - host: {{ .Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cicd-app-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    {{- end }}
{{- end }}
