apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cicd-app-chart.fullname" . }}-migration
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 40
      containers:
      - name: adonis-migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "yes | node ace migration:run && yes | node ace db:seed"]      
        env:
          - name: APP_KEY
            value: "{{ .Values.appKey }}"
          - name: PORT
            value: "{{ .Values.service.port }}"
          - name: FORCE_DB_MIGRATIONS
            value: "true"
          - name: HOST
            value: "0.0.0.0"
          - name: LOG_LEVEL
            value: "info"
          - name: SESSION_DRIVER
            value: "cookie"
          - name: NODE_ENV
            value: "production"
          - name: DB_HOST
            value: "{{ .Release.Name }}-postgresql"
          - name: DB_USER
            value: "{{ .Values.postgresql.auth.username }}"
          - name: DB_PASSWORD
            value: "{{ .Values.postgresql.auth.password }}"
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: "{{ .Values.postgresql.auth.database }}"
      restartPolicy: Never
