apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-app-chart.fullname" . }}
  labels:
    {{- include "cicd-app-chart.labels" . | nindent 4 }}
    {{- if .Values.prNumber }}
    app.kubernetes.io/pr: "{{ .Values.prNumber }}"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "cicd-app-chart.selectorLabels" . | nindent 4 }}
