apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-app-chart.fullname" . }}
  labels:
    {{- include "cicd-app-chart.labels" . | nindent 4 }}
    {{- if .Values.prNumber }}
    app.kubernetes.io/pr: "{{ .Values.prNumber }}"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if .Values.prNumber }}
      # Auto-calculate NodePort: 30000 + PR number
      nodePort: {{ add 30000 (int .Values.prNumber) }}
      {{- end }}
      {{- end }}
  selector:
    {{- include "cicd-app-chart.selectorLabels" . | nindent 4 }}
