{{- if .Values.application.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: {{ .Values.application.source.repoURL }}
    targetRevision: {{ .Values.application.source.targetRevision }}
    path: {{ .Values.application.source.path }}
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: {{ .Values.application.destination.server }}
    namespace: {{ .Values.application.destination.namespace }}

  {{- with .Values.application.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
