name: CI - Test and Docker Image
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE.md'
      - 'PULL_REQUEST_TEMPLATE.md'
      - 'ISSUE_TEMPLATE.md'
      - '.github/workflows/ci-release.yml'
      - '.github/workflows/ci-docker-image.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE.md'
      - 'PULL_REQUEST_TEMPLATE.md'
      - 'ISSUE_TEMPLATE.md'
      - '.github/workflows/ci-docker-image.yml'

jobs:
  build-adonis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

  test-adonis:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_DB: app
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Wait for Postgres
        run: sleep 10
      - name: Test Project
        run: npm run test

  push-image:
    runs-on: ubuntu-latest
    needs: [test-adonis, build-adonis] # Attendre que les tests passent avant de pousser
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # Utilisation du bon driver pour gérer le cache

      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: damienmathieu/city-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.TOKEN_GITHUB }}

      - name: Run Trivy Scanner image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: damienmathieu/city-api:latest
          format: table
          severity: HIGH,CRITICAL

      - name: Push Docker image
        if: success() && github.event_name != 'pull_request' # Only push if the scan passes and not in a pull request
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: damienmathieu/city-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.TOKEN_GITHUB }}
