name: CI - Docker Image
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE.md'
      - 'PULL_REQUEST_TEMPLATE.md'
      - 'ISSUE_TEMPLATE.md'
      - 'public/**'
      - 'resources/**'
      - 'start/**'
      - 'tests/**'
      - 'app/**'
      - 'bin/**'
      - 'app/**'
      - 'ace.js'
      - 'adonis'
      - 'config/**'
      - 'database/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/ci-all.yml'
      - '.github/workflows/ci-release.yml'

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # Utilisation du bon driver pour gérer le cache

      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: damienmathieu/city-api:unstable
          cache-from: type=gha
          cache-to: type=gha,mode=max
          github-token: ${{ secrets.TOKEN_GITHUB }}
          load: true

      - name: Run Trivy Scanner image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: damienmathieu/city-api:unstable
          format: table
          severity: HIGH,CRITICAL

      - name: Push Docker image
        if: success() # Only push if the scan passes
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: damienmathieu/city-api:unstable
          cache-from: type=gha
          github-token: ${{ secrets.TOKEN_GITHUB }}
